name: PRs to master
on: 
  pull_request_target:
    branches:
      - 'deploy/**'
    types: [closed]
jobs:
  merge-master-back-to-dev:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "mi-ran@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout testQA
          git pull
          echo "Auto-merge ${{ github.event.pull_request.base.ref }} back to testQA"
          git merge --no-ff ${{ github.event.pull_request.base.ref }} -m "Auto-merge ${{ github.event.pull_request.base.ref }} back to testQA"
          git push
