name: Sync multiple branches
on:
  pull_request:
    branches:
      - 'deploy/*'
    types: [closed]
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge development -> staging
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: testQA
          github_token: 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
