name: PRs to master
on: 
  push:
    branches: [deploy/**]
jobs:
  merge-master-back-to-dev:
    timeout-minutes: 2
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "mi-ran@github.com"
          git config --local user.name "Github Actions"
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout testQA
          git pull
          echo "Auto-merge ${{ github.ref_name }} back to testQA"
          git merge --no-ff ${{ github.ref_name }} -m "Auto-merge ${{ github.ref_name }} back to testQA"
          git push
    - name: run jenkins job
      run: |
        curl naver.com
