name: PRs to master
on: 
  push:
    branches: [deploy/**]
jobs:
  merge-master-back-to-dev:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Merge master back to dev
      run: |
          git fetch --unshallow
          git checkout testQA
          git pull
          echo "Auto-merge ${GITHUB_REF#refs/heads/} back to testQA"
          git merge --no-ff ${GITHUB_REF#refs/heads/} -m "Auto-merge ${GITHUB_REF#refs/heads/} back to testQA"
          git push
    - name: run jenkins job
      run: |
        curl naver.com?BRANCH=${GITHUB_REF#refs/heads/}
